<?php

/**
 * @author Cassiano Vellames <c.vellames@outlook.com>
 * @since 1.0.0
 */
final class NoteBean implements IBean, JsonSerializable {

    /**
     * @var int Id of the note. This is the primary key of table. The value is generated by the database
     */
    private $id;

    /**
     * @var UserBean User to which belongs it note
     */
    private $user;

    /**
     * @var string Title of note
     */
    private $title;

    /**
     * @var string Content of note
     */
    private $description;

    /**
     * @var DateTime Date and time that the note are created
     */
    private $created;

    /**
     * @var DateTime Date and time that the note are modified
     */
    private $modified;

    public function __construct(UserBean $user, string $title, string $description, DateTime $created, DateTime $modified, int $id = null){
        $this->user = $this->setUser($user);
        $this->title = $this->setTitle($title);
        $this->description = $this->setDescription($description);
        $this->created = $this->setCreated($created);
        $this->modified = $this->setModified($modified);
        $this->id = $this->setId($id);
    }

    public function getId() : int {
        return $this->id;
    }

    public function setId(int $id = null) {
        $this->id = $id;
    }

    public function getUser() : UserBean {
        return $this->user;
    }

    public function setUser(UserBean $user) {
        $this->user = $user;
    }

    public function getTitle() : string {
        return $this->title;
    }

    public function setTitle(string $title){
        $this->title = $title;
    }

    public function getDescription() : string {
        return $this->description;
    }

    public function setDescription(string $description){
        $this->description = $description;
    }

    public function getCreated() : DateTime{
        return $this->created;
    }

    public function setCreated(DateTime $created){
        $this->created = $created;
    }

    public function getModified() : DateTime{
        return $this->modified;
    }

    public function setModified(DateTime $modified){
        $this->modified = $modified;
    }

    /**
     * Specify data which should be serialized to JSON
     * @link http://php.net/manual/en/jsonserializable.jsonserialize.php
     * @return mixed data which can be serialized by <b>json_encode</b>,
     * which is a value of any type other than a resource.
     * @since 5.4.0
     */
    function jsonSerialize(){
        // TODO: Implement jsonSerialize() method.
    }
}
